### ISSUE TITLE
Add ability to connect to a socket

### ISSUE THREAD

**Issue by lepz0r** [yktoo/ymuse#10]
ymuse seems to refuse to connect to a socket as it says no such host

``WARNING player Failed to connect to MPD: DialAuthenticated() failed: dial tcp: lookup /home/cincinmasukmangkok/.config/mpd/socket: no such host``

**Comment by yktoo** [comment]
That's right, for now only the TCP connection is supported. It's essentially a limitation of the underlying `gompd` library.

You could use a localhost connection instead (provided that MPD is listening there).

**Comment by yktoo** [comment]
That's right, for now only the TCP connection is supported.

~~It's essentially a limitation of the underlying gompd library.~~ As it turns out, `gompd` perfectly supports sockets (using `unix` protocol). What's needed is a change of interface to allow entering the socket path.

In the meantime, you could use a localhost connection instead (provided that MPD is listening there).
