### ISSUE TITLE
Streams that will not work

### ISSUE THREAD

**Issue by dln949** [yktoo/ymuse#31]
Ymuse 0.16 snap package on Ubunut 18.04.  

Trying to add some streams from DI.FM, I enter this URL, for example:  

http://listen.di.fm/premium/discohouse.pls?listen_key=my_personal_key_for_my_DI.FM_account

But Ymuse will not play it, it produces this error message:  

"File discohouse.pls?listen_key=my_personal_key_for_my_DI.FM_account from http:/listen.di.fm/premium - Failed to decode http://http://listen.di.fm/premium/discohouse.pls?listen_key=my_personal_key_for_my_DI.FM_account"

I don't know what is wrong, this URL works great in several other applications that stream online radio stations.  

I am able to play other streams in Ymuse just fine, only these that have my DI.FM key are the ones that will not work.  

How do I make this station work in Ymuse?  

(P.S.:  Where will I find the file that has the streams that I have added?)

**Comment by yktoo** [comment]
This is most likely the error reported by MPD, which perhaps imposes some limitations or cannot digest the stream URL you've provided. Which means it's not caused by Ymuse.

Apart from that, the URL you've mentioned doesn't seem valid, so it may be a good idea to check that first.

All stream URLs are written out by Ymuse as a part of its config, which is normally located at `<YOUR_HOME_DIR>/.config/ymuse/config.json`.
