### ISSUE TITLE
Play / Add / Enqeue all songs of the library

### ISSUE THREAD

**Issue by topas-rec** [yktoo/ymuse#69]
Is it possible to add all songs or multiple albums at once of the library to the playlist?

I am unable to to that though I read the FAQ this time.

I tried to multi select albums or songs to then right click and append or so, but multi-select is not possible.
Also right clicking on the `Albums` entry shows the append entry as disabled.

If it is not possible I would like to suggest that feature.

Best wishes to everyone.

**Comment by yktoo** [comment]
You're right, it's not currently possible. Multiselection in the library seems a really unwieldy task, but you can easily click on "+" left of each item to add it to the queue, and then save the queue into a playlist.

I could've enabled adding the entire collection upon selecting the root "Files" element though. Looks like a valuable feature to me.

**Comment by topas-rec** [comment]
> but you can easily click on "+" left of each item to add it to the queue, and then save the queue into a playlist.

And since this doesn't has to be done daily - this is okay for now - at least for my music library size.

**Comment by yktoo** [comment]
Pushed to `dev`, but it's only available for the **Files** element for consistency.

Otherwise the list of tracks would need to be filtered during processing. For instance, tracks without a genre would have to be skipped when adding all by right-clicking "Genres → Replace the queue". This is hardly a realistic use case.

Therefore, since every track has a file, you can add/replace all library tracks by right-clicking "Files".

**Comment by yktoo** [comment]
**Update** the queue size limit appears [to be configurable](https://github.com/MusicPlayerDaemon/MPD/issues/478).

**Comment by topas-rec** [comment]
Oh thank you very much.

>  (Genre, Album, Artist are all optional).

You mean these metadata tags are not necessarily be filled at some files in the library?

**Comment by yktoo** [comment]
@topas-rec Exactly. They may all be empty, in which case it isn't logical to add those tracks to the queue.
